name: expense_tracker_assignment
description: "Expense Tracker application for Level 6 Mobile Development assignment."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State management
  provider: ^6.0.5

  # Local persistence
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Camera
  image_picker: ^1.0.4

  # Date formatting
  intl: ^0.19.0

  # Charts
  fl_chart: ^0.68.0

  # Notifications
  flutter_local_notifications: ^17.0.0

  
  firebase_core: ^2.24.2
  firebase_analytics: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
