name: expense_tracker_assignment
description: "Expense Tracker application for Level 6 Mobile Development assignment."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI icons
  cupertino_icons: ^1.0.8

  # State management
  provider: ^6.0.5

  # Local persistence
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Device feature (camera)
  image_picker: ^1.0.4

  # Date formatting
  intl: ^0.19.0

  # ðŸ“Š Charts (Pie & Bar graphs)
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
